image: node:latest

stages:
  - install
  - test
  - deploy

install:
  stage: install
  script: 
    - cd frontend
    - npm -v
    - npm install

    
test:
  image: node:latest
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  cache:
    paths:
    - node_modules/
    - .yarn
  script:
    - echo -e "Deploying frontend"
  only:
    - main