image: node:latest

before_script:
  - cd frontend
  - npm -v

stages:
  - install
  - test
  - deploy

install:
  stage: install
  script: 
    - npm install

    
test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  cache:
    paths:
    - node_modules/
    - .yarn
  script:
    - echo -e "Deploying frontend"
  only:
    - main