image: node:latest

stages:
  - test
  - deploy

before_script:
  - cd frontend
  - yarn install --cache-folder .yarn

    
test:
  stage: test
  script:
    - yarn -v
    - yarn test

deploy:
  stage: deploy
  cache:
    paths:
    - node_modules/
    - .yarn
  script:
    - echo -e "Deploying frontend"
  only:
    - main