image: node:latest

stages:
  - install
  - test
  - deploy

before_script:
  - cd frontend

install:
  stage: install
  cache:
    paths:
      - node_modules/
  script: 
    - npm -v
    - npm install

    
test:
  stage: test
  script:
    - npm -v
    - npm test

deploy:
  stage: deploy
  cache:
    paths:
    - node_modules/
    - .yarn
  script:
    - echo -e "Deploying frontend"
  only:
    - main