image: node:latest

stages:
  - install
  - test
  - deploy

install:
  stage: install
  script: 
    - echo -e "Testing frontend ci"
    - ls
    

test:
  stage: test
  script:
    - yarn test

deploy:
  stage: deploy
  script:
    - echo -e "Deploying frontend"
  only:
    - main