image: node:latest

before_script:
  - cd frontend
  - yarn install --cache-folder .yarn
  - yarn -v

stages:
  - install
  - test
  - deploy

install:
  stage: install
  script: 
    - yarn install

    
test:
  stage: test
  cache:
    paths:
    - node_modules/
    - .yarn
  script:
    - yarn test

deploy:
  stage: deploy
  cache:
    paths:
    - node_modules/
    - .yarn
  script:
    - echo -e "Deploying frontend"
  only:
    - main