image: node:latest

stages:
  - install
  - test
  - deploy

install:
  stage: install
  script: 
    - | 
      cd frontend
      npm install --global yarn
      yarn install

    
    

test:
  stage: test
  script:
    - yarn test

deploy:
  stage: deploy
  script:
    - echo -e "Deploying frontend"
  only:
    - main