default:
  image: gradle:alpine
  services:
    - mysql:latest
  

stages:
  - test
  - deploy

before_script:
  - cd backend
  - mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'comsc';"
  - sudo mysql -u root -e "FLUSH PRIVILEGES;"
  - sudo mysql -u root -pcomsc -e "DROP DATABASE IF EXISTS bubble;"
  - cd database
  - mysql -u root -pcomsc co_creative < schema.sql


test:
  stage: test
  script:
    - gradle test



deploy:
  stage: deploy
  script:
    - echo -e "Backend is being deployed here"
  only:
    - main
