default:
  image: gradle:alpine
  services:
    - mysql:latest

variables: 
  MYSQL_ROOT_PASSWORD: comsc
  

stages:
  - test
  - deploy

before_script:
  - cd backend
  - mysql -u root -pcomsc -e "DROP DATABASE IF EXISTS bubble;"
  - cd database
  - mysql -u root -pcomsc co_creative < schema.sql
  - cd ../


test:
  stage: test
  script:
    - gradle test



deploy:
  stage: deploy
  script:
    - echo -e "Backend is being deployed here"
  only:
    - main
